# Uncomment the lines below you want to change by removing the # in the beginning

devices([
  "iPhone 8 Plus",
  "iPhone 11 Pro Max"
])

languages([
  "en-US",
])

scheme 'LeagueMeKnowUITests'
output_directory "./fastlane/screenshots"

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot


stop_after_first_error true
clear_previous_screenshots false
reinstall_app false
clean false # clean the project before building
localize_simulator true
test_without_building true
derived_data_path "./build"
